- platform: modbus
  scan_interval: 1
  inputs:

    # Generator: http://jinja.quantprogramming.com/
    #{% for i in range(32) %}
    #    - name: Button-32DI-1-1-{{i}}
    #      slave: 1
    #      hub: 32DI-1
    #      address: {{i}}
    #      input_type: discrete_input
    #{% endfor %}

    - name: Button-32DI-1-1-0
      slave: 1
      hub: 32DI-1
      address: 0
      input_type: discrete_input

    - name: Button-32DI-1-1-1
      slave: 1
      hub: 32DI-1
      address: 1
      input_type: discrete_input

    - name: Button-32DI-1-1-2
      slave: 1
      hub: 32DI-1
      address: 2
      input_type: discrete_input

    - name: Button-32DI-1-1-3
      slave: 1
      hub: 32DI-1
      address: 3
      input_type: discrete_input

    - name: Button-32DI-1-1-4
      slave: 1
      hub: 32DI-1
      address: 4
      input_type: discrete_input

    - name: Button-32DI-1-1-5
      slave: 1
      hub: 32DI-1
      address: 5
      input_type: discrete_input

    - name: Button-32DI-1-1-6
      slave: 1
      hub: 32DI-1
      address: 6
      input_type: discrete_input

    - name: Button-32DI-1-1-7
      slave: 1
      hub: 32DI-1
      address: 7
      input_type: discrete_input

    - name: Button-32DI-1-1-8
      slave: 1
      hub: 32DI-1
      address: 8
      input_type: discrete_input

    - name: Button-32DI-1-1-9
      slave: 1
      hub: 32DI-1
      address: 9
      input_type: discrete_input

    - name: Button-32DI-1-1-10
      slave: 1
      hub: 32DI-1
      address: 10
      input_type: discrete_input

    - name: Button-32DI-1-1-11
      slave: 1
      hub: 32DI-1
      address: 11
      input_type: discrete_input

    - name: Button-32DI-1-1-12
      slave: 1
      hub: 32DI-1
      address: 12
      input_type: discrete_input

    - name: Button-32DI-1-1-13
      slave: 1
      hub: 32DI-1
      address: 13
      input_type: discrete_input

    - name: Button-32DI-1-1-14
      slave: 1
      hub: 32DI-1
      address: 14
      input_type: discrete_input

    - name: Button-32DI-1-1-15
      slave: 1
      hub: 32DI-1
      address: 15
      input_type: discrete_input

    - name: Button-32DI-1-1-16
      slave: 1
      hub: 32DI-1
      address: 16
      input_type: discrete_input

    - name: Button-32DI-1-1-17
      slave: 1
      hub: 32DI-1
      address: 17
      input_type: discrete_input

    - name: Button-32DI-1-1-18
      slave: 1
      hub: 32DI-1
      address: 18
      input_type: discrete_input

    - name: Button-32DI-1-1-19
      slave: 1
      hub: 32DI-1
      address: 19
      input_type: discrete_input

    - name: Button-32DI-1-1-20
      slave: 1
      hub: 32DI-1
      address: 20
      input_type: discrete_input

    - name: Button-32DI-1-1-21
      slave: 1
      hub: 32DI-1
      address: 21
      input_type: discrete_input

    - name: Button-32DI-1-1-22
      slave: 1
      hub: 32DI-1
      address: 22
      input_type: discrete_input

    - name: Button-32DI-1-1-23
      slave: 1
      hub: 32DI-1
      address: 23
      input_type: discrete_input

    - name: Button-32DI-1-1-24
      slave: 1
      hub: 32DI-1
      address: 24
      input_type: discrete_input

    - name: Button-32DI-1-1-25
      slave: 1
      hub: 32DI-1
      address: 25
      input_type: discrete_input

    - name: Button-32DI-1-1-26
      slave: 1
      hub: 32DI-1
      address: 26
      input_type: discrete_input

    - name: Button-32DI-1-1-27
      slave: 1
      hub: 32DI-1
      address: 27
      input_type: discrete_input

    - name: Button-32DI-1-1-28
      slave: 1
      hub: 32DI-1
      address: 28
      input_type: discrete_input

    - name: Button-32DI-1-1-29
      slave: 1
      hub: 32DI-1
      address: 29
      input_type: discrete_input

    - name: Button-32DI-1-1-30
      slave: 1
      hub: 32DI-1
      address: 30
      input_type: discrete_input

    - name: Button-32DI-1-1-31
      slave: 1
      hub: 32DI-1
      address: 31
      input_type: discrete_input
