
  - name: 32DO-1
    type: tcp
    host: 192.168.82.76
    port: 502
    binary_sensors:

      - name: Sensor-32DO-1-000
        address: 0
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-001
        address: 1
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-002
        address: 2
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-003
        address: 3
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-004
        address: 4
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-005
        address: 5
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-006
        address: 6
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-007
        address: 7
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-008
        address: 8
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-009
        address: 9
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-010
        address: 10
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-011
        address: 11
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-012
        address: 12
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-013
        address: 13
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-014
        address: 14
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-015
        address: 15
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-016
        address: 16
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-017
        address: 17
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-018
        address: 18
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-019
        address: 19
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-020
        address: 20
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-021
        address: 21
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-022
        address: 22
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-023
        address: 23
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-024
        address: 24
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-025
        address: 25
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-026
        address: 26
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-027
        address: 27
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-028
        address: 28
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-029
        address: 29
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-030
        address: 30
        slave: 1
        scan_interval: 1

      - name: Sensor-32DO-1-031
        address: 31
        slave: 1
        scan_interval: 1

    switches:

      - name: Switch-32DO-1-000
        address: 0
        write_type: coil
        verify:
          address: 0

      - name: Switch-32DO-1-001
        address: 1
        write_type: coil
        verify:
          address: 1

      - name: Switch-32DO-1-002
        address: 2
        write_type: coil
        verify:
          address: 2

      - name: Switch-32DO-1-003
        address: 3
        write_type: coil
        verify:
          address: 3

      - name: Switch-32DO-1-004
        address: 4
        write_type: coil
        verify:
          address: 4

      - name: Switch-32DO-1-005
        address: 5
        write_type: coil
        verify:
          address: 5

      - name: Switch-32DO-1-006
        address: 6
        write_type: coil
        verify:
          address: 6

      - name: Switch-32DO-1-007
        address: 7
        write_type: coil
        verify:
          address: 7

      - name: Switch-32DO-1-008
        address: 8
        write_type: coil
        verify:
          address: 8

      - name: Switch-32DO-1-009
        address: 9
        write_type: coil
        verify:
          address: 9

      - name: Switch-32DO-1-010
        address: 10
        write_type: coil
        verify:
          address: 10

      - name: Switch-32DO-1-011
        address: 11
        write_type: coil
        verify:
          address: 11

      - name: Switch-32DO-1-012
        address: 12
        write_type: coil
        verify:
          address: 12

      - name: Switch-32DO-1-013
        address: 13
        write_type: coil
        verify:
          address: 13

      - name: Switch-32DO-1-014
        address: 14
        write_type: coil
        verify:
          address: 14

      - name: Switch-32DO-1-015
        address: 15
        write_type: coil
        verify:
          address: 15

      - name: Switch-32DO-1-016
        address: 16
        write_type: coil
        verify:
          address: 16

      - name: Switch-32DO-1-017
        address: 17
        write_type: coil
        verify:
          address: 17

      - name: Switch-32DO-1-018
        address: 18
        write_type: coil
        verify:
          address: 18

      - name: Switch-32DO-1-019
        address: 19
        write_type: coil
        verify:
          address: 19

      - name: Switch-32DO-1-020
        address: 20
        write_type: coil
        verify:
          address: 20

      - name: Switch-32DO-1-021
        address: 21
        write_type: coil
        verify:
          address: 21

      - name: Switch-32DO-1-022
        address: 22
        write_type: coil
        verify:
          address: 22

      - name: Switch-32DO-1-023
        address: 23
        write_type: coil
        verify:
          address: 23

      - name: Switch-32DO-1-024
        address: 24
        write_type: coil
        verify:
          address: 24

      - name: Switch-32DO-1-025
        address: 25
        write_type: coil
        verify:
          address: 25

      - name: Switch-32DO-1-026
        address: 26
        write_type: coil
        verify:
          address: 26

      - name: Switch-32DO-1-027
        address: 27
        write_type: coil
        verify:
          address: 27

      - name: Switch-32DO-1-028
        address: 28
        write_type: coil
        verify:
          address: 28

      - name: Switch-32DO-1-029
        address: 29
        write_type: coil
        verify:
          address: 29

      - name: Switch-32DO-1-030
        address: 30
        write_type: coil
        verify:
          address: 30

      - name: Switch-32DO-1-031
        address: 31
        write_type: coil
        verify:
          address: 31


#  - name: 32DI-1
#    type: tcp
#    host: 192.168.5.77
#    port: 502