esphome:
  name: poetest0
  platform: ESP32
  board: esp-wrover-kit

# wifi:
#   ssid: 'WifiDM'
#   password: '4114office'

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: 's3M322AWyAuV'

ota:
  password: 's3M322AWyAuV'

# Example configuration entry
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 0
  power_pin: GPIO12

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.90
    gateway: 192.168.1.1
    subnet: 255.255.255.0