esphome:
  name: wesp0
  platform: ESP32
  board: esp-wrover-kit
  arduino_version: latest
  
# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: 's3M322AWyAuV'

ota:
  password: 's3M322AWyAuV'
  
# Example configuration entry
# wifi:
#   ssid: Aldebaran
#   password: emanuelew1f1
#   domain: .mira.buildings.emanueletessore.com
  
# Example configuration entry
ethernet:
  type: LAN8720
  mdc_pin: GPIO16
  mdio_pin: GPIO17
  clk_mode: GPIO0_IN
  phy_addr: 0
  domain: .mira.buildings.emanueletessore.com
  # use_address: 192.168.82.129

  # Optional manual IP
  # manual_ip:
  #   static_ip: 192.168.1.90
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0
  
binary_sensor:
  - platform: gpio
    name: "test button"
    pin:
      number: GPIO4
      inverted: True
      mode: INPUT_PULLUP
    on_press:
      then:
        - light.toggle: test_blue_led_light_0

output:
  - platform: ledc
    pin: GPIO23
    id: test_blue_led_output_0
    
light:
  - platform: monochromatic
    name: "Test blue LED"
    output: test_blue_led_output_0
    id: test_blue_led_light_0
    
web_server:
  port: 80
    