# generator: http://jinja.quantprogramming.com/
# {% for i in range(32) %}
#  - name: Switch-32DO-1-{{ i }}
#    hub: 32DO-1
#    coil: {{ i }}
#    slave: 1
#{% endfor %}
- platform: modbus
  scan_interval: 1
  coils:

    - name: Switch-32DO-1-0
      hub: 32DO-1
      coil: 0
      slave: 1

    - name: Switch-32DO-1-1
      hub: 32DO-1
      coil: 1
      slave: 1

    - name: Switch-32DO-1-2
      hub: 32DO-1
      coil: 2
      slave: 1

    - name: Switch-32DO-1-3
      hub: 32DO-1
      coil: 3
      slave: 1

    - name: Switch-32DO-1-4
      hub: 32DO-1
      coil: 4
      slave: 1

    - name: Switch-32DO-1-5
      hub: 32DO-1
      coil: 5
      slave: 1

    - name: Switch-32DO-1-6
      hub: 32DO-1
      coil: 6
      slave: 1

    - name: Switch-32DO-1-7
      hub: 32DO-1
      coil: 7
      slave: 1

    - name: Switch-32DO-1-8
      hub: 32DO-1
      coil: 8
      slave: 1

    - name: Switch-32DO-1-9
      hub: 32DO-1
      coil: 9
      slave: 1

    - name: Switch-32DO-1-10
      hub: 32DO-1
      coil: 10
      slave: 1

    - name: Switch-32DO-1-11
      hub: 32DO-1
      coil: 11
      slave: 1

    - name: Switch-32DO-1-12
      hub: 32DO-1
      coil: 12
      slave: 1

    - name: Switch-32DO-1-13
      hub: 32DO-1
      coil: 13
      slave: 1

    - name: Switch-32DO-1-14
      hub: 32DO-1
      coil: 14
      slave: 1

    - name: Switch-32DO-1-15
      hub: 32DO-1
      coil: 15
      slave: 1

    - name: Switch-32DO-1-16
      hub: 32DO-1
      coil: 16
      slave: 1

    - name: Switch-32DO-1-17
      hub: 32DO-1
      coil: 17
      slave: 1

    - name: Switch-32DO-1-18
      hub: 32DO-1
      coil: 18
      slave: 1

    - name: Switch-32DO-1-19
      hub: 32DO-1
      coil: 19
      slave: 1

    - name: Switch-32DO-1-20
      hub: 32DO-1
      coil: 20
      slave: 1

    - name: Switch-32DO-1-21
      hub: 32DO-1
      coil: 21
      slave: 1

    - name: Switch-32DO-1-22
      hub: 32DO-1
      coil: 22
      slave: 1

    - name: Switch-32DO-1-23
      hub: 32DO-1
      coil: 23
      slave: 1

    - name: Switch-32DO-1-24
      hub: 32DO-1
      coil: 24
      slave: 1

    - name: Switch-32DO-1-25
      hub: 32DO-1
      coil: 25
      slave: 1

    - name: Switch-32DO-1-26
      hub: 32DO-1
      coil: 26
      slave: 1

    - name: Switch-32DO-1-27
      hub: 32DO-1
      coil: 27
      slave: 1

    - name: Switch-32DO-1-28
      hub: 32DO-1
      coil: 28
      slave: 1

    - name: Switch-32DO-1-29
      hub: 32DO-1
      coil: 29
      slave: 1

    - name: Switch-32DO-1-30
      hub: 32DO-1
      coil: 30
      slave: 1

    - name: Switch-32DO-1-31
      hub: 32DO-1
      coil: 31
      slave: 1


