# generator: http://jinja.quantprogramming.com/
#{% for i in range(32) %}
#- name: Register-32DO-1-{{ i }}
#  hub: 32DO-1
#  slave: 1
#  register: {{ i }}
#  command_on: 1
#  command_off: 0
#{% endfor %}

- platform: modbus
  scan_interval: 1
  registers:
    - name: Register-32DO-1-0
      hub: 32DO-1
      slave: 1
      register: 0
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-1
      hub: 32DO-1
      slave: 1
      register: 1
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-2
      hub: 32DO-1
      slave: 1
      register: 2
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-3
      hub: 32DO-1
      slave: 1
      register: 3
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-4
      hub: 32DO-1
      slave: 1
      register: 4
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-5
      hub: 32DO-1
      slave: 1
      register: 5
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-6
      hub: 32DO-1
      slave: 1
      register: 6
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-7
      hub: 32DO-1
      slave: 1
      register: 7
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-8
      hub: 32DO-1
      slave: 1
      register: 8
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-9
      hub: 32DO-1
      slave: 1
      register: 9
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-10
      hub: 32DO-1
      slave: 1
      register: 10
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-11
      hub: 32DO-1
      slave: 1
      register: 11
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-12
      hub: 32DO-1
      slave: 1
      register: 12
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-13
      hub: 32DO-1
      slave: 1
      register: 13
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-14
      hub: 32DO-1
      slave: 1
      register: 14
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-15
      hub: 32DO-1
      slave: 1
      register: 15
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-16
      hub: 32DO-1
      slave: 1
      register: 16
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-17
      hub: 32DO-1
      slave: 1
      register: 17
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-18
      hub: 32DO-1
      slave: 1
      register: 18
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-19
      hub: 32DO-1
      slave: 1
      register: 19
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-20
      hub: 32DO-1
      slave: 1
      register: 20
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-21
      hub: 32DO-1
      slave: 1
      register: 21
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-22
      hub: 32DO-1
      slave: 1
      register: 22
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-23
      hub: 32DO-1
      slave: 1
      register: 23
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-24
      hub: 32DO-1
      slave: 1
      register: 24
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-25
      hub: 32DO-1
      slave: 1
      register: 25
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-26
      hub: 32DO-1
      slave: 1
      register: 26
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-27
      hub: 32DO-1
      slave: 1
      register: 27
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-28
      hub: 32DO-1
      slave: 1
      register: 28
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-29
      hub: 32DO-1
      slave: 1
      register: 29
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-30
      hub: 32DO-1
      slave: 1
      register: 30
      command_on: 1
      command_off: 0

    - name: Register-32DO-1-31
      hub: 32DO-1
      slave: 1
      register: 31
      command_on: 1
      command_off: 0